workflows:
  android-workflow:
    name: Android Flutter Workflow
    max_build_duration: 60
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Get Flutter packages
        script: |
          cd frontend
          flutter pub get
      - name: Build Android APK
        script: |
          cd frontend
          flutter build apk --debug
    artifacts:
      - frontend/build/app/outputs/**/*.apk